"""Generate BASELINE.md from a results JSON produced by run.py.

Usage: ./venv/bin/python scripts/permuter/bench/gen_baseline_md.py RESULTS.json
"""
import json
import sys
from pathlib import Path

results = json.loads(Path(sys.argv[1]).read_text())
m = results["headline_metrics"]
p = results["profile_breakdown"]
seed = results["seed_config"]

w100 = m["wall_clock_to_first_100_seconds"]
w100_str = f"{w100} s" if w100 is not None else "n/a (no function reached 100% on this run)"

from collections import Counter
band_counts = Counter(f["band"] for f in results["functions"])
band_str = " / ".join(f"{band_counts.get(b, 0)} {b}" for b in ("high", "mid", "low"))

lines = []
A = lines.append
A("# Permuter Bench Baseline (A0)")
A("")
A(f"Generated by `scripts/permuter/bench/run.py` over the pinned "
  f"{results['n_functions']}-function bench set (`bench_set.json`). Re-run with "
  "the same command to get a comparable delta; every later performance PR "
  "should post its own row.")
A("")
A(f"- **Run timestamp:** {results['timestamp']}")
A(f"- **git HEAD:** `{results['git_head']}`")
A(f"- **functions:** {results['n_functions']}  ({band_str})")
A(f"- **seed config:** patterns=`{seed['patterns']}`, max_rounds={seed['max_rounds']}, "
  f"max_variants={seed['max_variants']}, plateau_limit={seed['plateau_limit']}, "
  f"compose={seed['compose']}, workers={seed['workers']}, "
  f"PYTHONHASHSEED={seed['pythonhashseed']}")
A(f"- **cache:** fresh/isolated (cold path) — every variant exercises a real "
  "compile + objdiff")
A(f"- **overall wall:** {results['overall_wall_seconds']} s")
A("")
A("> Caveat: this baseline was captured while several other permuter sweeps")
A("> were running concurrently on the same host, so the *wall-clock* numbers")
A("> are inflated by CPU contention. The per-call subprocess costs")
A("> (`per_call_ms` below) are the contention-robust signal for the A2/A4")
A("> decision; re-run on a quiet host for a clean wall-clock baseline.")
A("")
A("## Headline Metrics")
A("")
A("| Metric | Baseline |")
A("|--------|----------|")
A(f"| variants / second | {m['variants_per_second']} |")
A(f"| wins / 100 attempts | {m['wins_per_100_attempts']}  "
  f"({m['functions_improved']}/{results['n_functions']} functions improved) |")
A(f"| wall-clock to first 100% | {w100_str} |")
A("")
A(f"Supporting: {m['total_variants_scored']} variants scored across the set; "
  f"scoring wall {m['scoring_wall_seconds']} s; "
  f"{m['functions_reached_100']} functions reached 100%.")
A("")
A("## Per-variant profiling breakdown")
A("")
if p.get("enabled"):
    A("Wall-clock attribution across the roadmap's buckets. Two denominators:")
    A("")
    A("- **percent_of_attributed** — share of instrumented work. The honest")
    A("  \"where does the work go\" view (sums to ~100% over real work).")
    A("- **percent_of_wall** — share of single-thread wall. With parallel")
    A("  compile workers the compile buckets can exceed their wall share")
    A("  because N threads accrue time simultaneously.")
    A("")
    A("| Bucket | seconds | % attributed | % wall |")
    A("|--------|---------|--------------|--------|")
    for name in sorted(p["seconds"], key=lambda k: -p["seconds"][k]):
        A(f"| {name} | {p['seconds'][name]} | "
          f"{p['percent_of_attributed'].get(name, 0)} | "
          f"{p['percent_of_wall'].get(name, 0)} |")
    A("")
    A(f"**Measured spawn floors:** "
      + ", ".join(f"{k} = {v} ms" for k, v in p["spawn_floors_ms"].items())
      + ".  ")
    A("(The roadmap's unverified \"~80 ms objdiff spawn\" is replaced by the")
    A(f"measured objdiff spawn floor of {p['spawn_floors_ms'].get('objdiff')} ms.)")
    A("")
    A("### Per-call subprocess cost (the A2/A4 decision input)")
    A("")
    A("| subprocess | calls | spawn ms | run ms | spawn % of subprocess time |")
    A("|------------|-------|----------|--------|----------------------------|")
    for kind, d in p.get("per_call_ms", {}).items():
        A(f"| {kind} | {d['calls']} | {d['spawn_ms']} | {d['run_ms']} | "
          f"{d['spawn_share_pct']}% |")
    A("")
else:
    A("Profiling was not enabled for this run (pass `--profile`).")
    A("")
A("## How to reproduce")
A("")
A("```bash")
A("# sandbox must be disabled — wibo/cl.exe write objects the sandbox blocks")
A("PYTHONHASHSEED=0 ./venv/bin/python -m scripts.permuter.bench.run --profile \\")
A("    --out scripts/permuter/bench/baseline-results.json")
A("```")
A("")

Path("scripts/permuter/bench/BASELINE.md").write_text("\n".join(lines))
print("wrote BASELINE.md")
print("\nKEY NUMBERS:")
print("  variants/sec:", m["variants_per_second"])
print("  wins/100:", m["wins_per_100_attempts"])
print("  wall-to-100:", w100)
if p.get("enabled"):
    print("  spawn floors ms:", p["spawn_floors_ms"])
    print("  per_call_ms:", json.dumps(p.get("per_call_ms")))
    print("  pct_attributed:", json.dumps(p["percent_of_attributed"]))
