#!/usr/bin/env python3
"""Every row certified COMPLETE in `decomp.db` that is NOT 100 in a fresh report.

A `COMPLETE` verdict tells every future agent to stop working on the function.
When the source moves under it -- a header edit, a refactor, a ruler change --
the certificate keeps saying "done" about code that no longer matches.  That is
certificate rot, and this is the query that finds it.

WHY THIS IS A SCRIPT AND NOT A NUMBER IN A DOC
==============================================
`docs/STATE_OF_THE_DECOMP.md` carried "this count is 0" from 2026-08-19 to
2026-08-31, by which time it was 27.  Every hardcoded worklist this project has
written rotted within weeks.  So the doc names this command and this command
prints the count.

WHY IT READS report.json AND NOT A COLUMN
=========================================
Three surfaces claim to be the match percentage and only one is canonical:

  * `functions.current_percent` -- objdiff's *fuzzy* score.  Drifts up to 7.6 pp
    from canonical; `verdict='COMPLETE' AND current_percent < 100` returns a
    phantom population.
  * `functions.match_percent_normalized` -- the right ruler, but a CACHE.  It is
    written only by `scripts/sync_match_percent.py --promote`, so it is exactly
    as fresh as the last person who ran that.  On 2026-08-31 it disagreed with a
    fresh report in BOTH directions: it hid two rows that had rotted since the
    last sync, and listed seven that had since been fixed.
  * `report.json`'s `match_percent_normalized` -- an exact score-weighted f32,
    unrounded, regenerated by `ninja`.  This is the one.

So: run `ninja` first.  This script refuses a report older than the newest
object it can see, rather than quietly answering from a stale one.

WHAT IS DELIBERATELY EXCLUDED
=============================
A report row with no `fuzzy_match_percent` is a function we emit NO BODY for --
objdiff scores it 0.0 because there is nothing to pair, not because it mismatches.
`default/link_glue`'s 66 rows are all of that shape and would otherwise dominate
the population with nine false positives.  Counted and printed, never silent.

    python3 scripts/analysis/cert_rot_census.py --db <main>/decomp.db
    python3 scripts/analysis/cert_rot_census.py --db ... --json-out rot.json
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def find_report(project: Path) -> Path:
    cands = sorted((project / "build").glob("*/report.json"))
    if not cands:
        raise SystemExit(f"no build/<title>/report.json under {project} -- run ninja")
    return max(cands, key=lambda p: p.stat().st_mtime)


def load_report(path: Path) -> tuple[dict[str, tuple[float, int, str]], dict[str, int]]:
    """symbol -> (normalized%, size, unit), plus the drop counts."""
    data = json.loads(path.read_text())
    best: dict[str, tuple[float, int, str]] = {}
    drops = {"no-normalized-score": 0, "no-fuzzy-score-nothing-to-pair": 0}
    for unit in data["units"]:
        for fn in unit.get("functions") or []:
            pct = fn.get("match_percent_normalized")
            if pct is None:
                drops["no-normalized-score"] += 1
                continue
            if fn.get("fuzzy_match_percent") is None:
                # We emit no body for this symbol; 0.0 here is "unpaired", not
                # "mismatched".  link_glue is entirely of this shape.
                drops["no-fuzzy-score-nothing-to-pair"] += 1
                continue
            name = fn["name"]
            # A symbol can appear in several units; the best pairing is the
            # measurement (objdiff itself reports "multiple instances found").
            if name not in best or pct > best[name][0]:
                best[name] = (pct, int(fn["size"]), unit["name"])
    return best, drops


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--db", default=str(REPO_ROOT / "decomp.db"),
                    help="the MAIN checkout's decomp.db -- a worktree has a tripwire")
    ap.add_argument("--project", default=str(REPO_ROOT))
    ap.add_argument("--report", default=None)
    ap.add_argument("--include-excluded", action="store_true",
                    help="also report rows with excluded=1 (still certificates)")
    ap.add_argument("--json-out", default=None)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the population is non-empty")
    a = ap.parse_args(argv)

    report = Path(a.report) if a.report else find_report(Path(a.project))
    best, drops = load_report(report)

    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    from orchestrator.database import check_not_shadow_db   # noqa: E402
    check_not_shadow_db(a.db)                               # names the real DB

    con = sqlite3.connect(f"file:{a.db}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    rows = con.execute(
        "SELECT symbol, size, unit, excluded, current_percent, "
        "       match_percent_normalized AS db_norm, verdict_reason "
        "  FROM functions WHERE verdict = 'COMPLETE'").fetchall()

    rot, unpaired = [], 0
    for r in rows:
        m = best.get(r["symbol"])
        if m is None:
            unpaired += 1
            continue
        if m[0] < 100.0:
            rot.append({"symbol": r["symbol"], "report_unit": m[2],
                        "size": m[1], "normalized": m[0],
                        "excluded": r["excluded"],
                        "db_current_percent": r["current_percent"],
                        "db_match_percent_normalized": r["db_norm"],
                        "verdict_reason": r["verdict_reason"]})
    con.close()
    rot.sort(key=lambda d: d["normalized"])
    shown = rot if a.include_excluded else [d for d in rot if not d["excluded"]]

    print(f"report      : {report}")
    print(f"db          : {a.db}")
    print(f"COMPLETE    : {len(rows)} rows")
    print(f"  unpaired  : {unpaired} (no comparable row in the report -- mostly "
          f"merged_* ICF survivors)")
    for k, v in drops.items():
        print(f"  dropped   : {v:6} report rows  {k}")
    print()
    hidden = [d for d in rot if d["excluded"]] if not a.include_excluded else []
    tail = (f"  (+{len(hidden)} excluded=1 rows, {sum(d['size'] for d in hidden)} B,"
            f" hidden -- --include-excluded to see them)") if hidden else ""
    print(f"CERT ROT    : {len(shown)} rows, "
          f"{sum(d['size'] for d in shown)} bytes{tail}")
    for d in shown:
        print(f"{d['normalized']:11.6f}  {d['size']:6}B  {d['symbol']}")
        print(f"{'':13}{d['report_unit']}   db_norm={d['db_match_percent_normalized']} "
              f"current_percent={d['db_current_percent']}")
    if a.json_out:
        Path(a.json_out).write_text(json.dumps(rot, indent=1))
        print(f"\nwrote {a.json_out}")
    return 1 if (a.check and shown) else 0


if __name__ == "__main__":
    raise SystemExit(main())
