#!/usr/bin/env python3
"""Render the synthetic MSVC map declaring dc3's WITNESSED ICF symbol folds.

Why this exists
---------------
Retail DC3 was linked with MSVC ``/OPT:ICF``, which folds byte-identical
COMDATs: several source-level spellings survive at ONE address in the shipped
image. The target objects can therefore only ever name the survivor, while our
compiled objects emit the spelling their own translation unit references. Any
by-name relocation comparison -- objdiff's ``reloc_eq`` included -- flags a
``[sym]`` mismatch on a call site that is the same bytes to the same code.

objdiff already has the seam for this: ``objdiff.json``'s ``map_file`` ->
``objdiff-core/src/obj/map_file.rs`` ``parse_msvc_map``, which groups every
symbol name sharing an 8-hex address and treats names in a group as
reloc-name-equal. We have no real MSVC ``.map``, so we emit a *synthetic* one
whose entire content is the witnessed folds: one line per group member, all
carrying the survivor's address, so the parser buckets them together. No
objdiff source change is required.

The evidence, and what is NOT admitted
--------------------------------------
Every group in ``scripts/symbol_aliases.json`` is a BODY-TEST WITNESS from
decomp-synth's ``tools/revcomp/probes/probe_icf_foldtest.py``: retail bytes at
the survivor address are relocation-invariantly identical (immediates masked,
``60 00 00 00`` padding trimmed, one-level thunk chase) to our compiled body for
each folded spelling. **Name shapes are arguments, not witnesses** -- an earlier
triage declared every ``merged_``-prefixed target benign from its name and the
body test then found 9 of 33 such sites genuinely different functions.

That file holds the VALIDATOR-ACCEPTED classes only. This renderer does not
validate and objdiff never does, so "the map contains no class the validator
refused" has to be true of the input file itself. Regenerate the input with
decomp-synth's ``tools/il_witness/build_icf_alias_inputs.py`` (build, then
``--validate ... --emit-map``); do not hand-add a group here.

Note that the CONSUMER-side gate is independent and stricter: decomp-synth's
``tools/il_witness/symbol_equivalences.py`` re-derives the verdict from the tree
it is grading on every load, and will drop a class this map still contains once
the tree stops supporting it. That direction is safe (the grader is then
stricter than the judge for that one class); the reverse would not be.

Usage
-----
    python3 scripts/gen_icf_alias_map.py             # write build/373307D9/icf_aliases.map
    python3 scripts/gen_icf_alias_map.py --check     # exit 1 if the map is stale
    python3 scripts/gen_icf_alias_map.py --out PATH  # custom output path

``tools/project.py`` runs this at configure time and wires ``map_file`` only if
the output exists, so a fresh tree without the generated map still builds -- no
map means no equivalences, which is the pre-ICF behaviour.
"""

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
BUILD_ID = "373307D9"
DEFAULT_ALIASES = PROJECT_ROOT / "scripts" / "symbol_aliases.json"
DEFAULT_OUT = PROJECT_ROOT / "build" / BUILD_ID / "icf_aliases.map"

# parse_msvc_map's regex (objdiff-core/src/obj/map_file.rs) is
#   ^\s*\d{4}:[0-9a-fA-F]+\s+(\S+)\s+([0-9a-fA-F]{8})\s+
# i.e.  SSSS:OOOOOOOO   <symbol>   AAAAAAAA   <rest>
# Group 1 is the symbol, group 2 the address used to bucket the fold.
MAP_LINE = " 0001:00000000       {sym:<60} {addr}  f i icf_aliases.synthetic\n"

HEADER = (
    "; SYNTHETIC ICF-alias map -- generated by scripts/gen_icf_alias_map.py\n"
    "; DO NOT EDIT BY HAND. Source of truth: scripts/symbol_aliases.json\n"
    "; Consumed by objdiff via objdiff.json 'map_file' -> parse_msvc_map ->\n"
    "; symbol_equivalences (objdiff-core reloc_eq). Every group below is a\n"
    "; BODY-TEST WITNESS: retail bytes at the survivor address are\n"
    "; relocation-invariantly identical to our compiled body for each folded\n"
    "; spelling. No group is admitted from a name shape.\n"
    ";\n"
    "; Address                        Publics by Value\n"
)


def load_groups(aliases_path: Path) -> list:
    return json.loads(aliases_path.read_text()).get("groups", [])


def normalize_addr(addr: str) -> str:
    """The 8-uppercase-hex form parse_msvc_map expects."""
    return f"{int(str(addr).lower().removeprefix('0x'), 16):08X}"


def render_map(groups: list) -> str:
    """A group with no address is SKIPPED, not emitted at address 0.

    Colliding unrelated groups on a fake address would hand objdiff an
    equivalence class nothing witnessed.
    """
    out = [HEADER]
    for g in groups:
        if not g.get("address"):
            continue
        addr = normalize_addr(g["address"])
        out.append(f"; --- ICF group {g.get('name', addr)} @ {addr} ---\n")
        for sym in [g["survivor"], *g.get("folded", [])]:
            out.append(MAP_LINE.format(sym=sym, addr=addr))
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--aliases", default=str(DEFAULT_ALIASES),
                    help="alias group JSON (default: %(default)s)")
    ap.add_argument("--out", default=str(DEFAULT_OUT),
                    help="output .map path (default: %(default)s)")
    ap.add_argument("--check", action="store_true",
                    help="verify the output is up to date; exit 1 if stale")
    args = ap.parse_args()

    aliases_path = Path(args.aliases)
    if not aliases_path.is_file():
        print(f"ERROR: no alias file at {aliases_path}", file=sys.stderr)
        return 1
    groups = load_groups(aliases_path)
    content = render_map(groups)

    out_path = Path(args.out)
    if args.check:
        if not out_path.is_file():
            print(f"STALE: {out_path} does not exist", file=sys.stderr)
            return 1
        if out_path.read_text() != content:
            print(f"STALE: {out_path} differs from generated content", file=sys.stderr)
            return 1
        print(f"OK: {out_path} up to date ({len(groups)} ICF groups)")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    n_syms = sum(1 + len(g.get("folded", [])) for g in groups)
    print(f"wrote {out_path}: {len(groups)} ICF groups, {n_syms} symbol lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
