#!/usr/bin/env python3
"""Sync objdiff results from report.json into decomp.db.

Reads the report generated by `ninja build/373307D9/report.json` (which runs
objdiff-cli internally against every object file) and updates every function's
current_percent, size, and demangled name in the database.

Usage:
    ninja build/373307D9/report.json && python3 scripts/sync_match_percent.py

Options:
    python3 scripts/sync_match_percent.py --build          # run ninja first
    python3 scripts/sync_match_percent.py --dry-run        # preview only
    python3 scripts/sync_match_percent.py --promote        # promote 100% -> COMPLETE
    python3 scripts/sync_match_percent.py --unit 'system/char/*'
    python3 scripts/sync_match_percent.py -v               # show every change
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REPORT = REPO_ROOT / "build" / "373307D9" / "report.json"
DEFAULT_DB = REPO_ROOT / "decomp.db"

SDK_UNIT_PREFIXES = [
    "default/xdk/",
]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Sync objdiff report.json into decomp.db",
    )
    p.add_argument("--report", type=Path, default=DEFAULT_REPORT,
                   help=f"Path to report.json (default: {DEFAULT_REPORT})")
    p.add_argument("--db", type=Path, default=DEFAULT_DB,
                   help=f"Path to decomp.db (default: {DEFAULT_DB})")
    p.add_argument("--build", action="store_true",
                   help="Run ninja to rebuild report.json before syncing")
    p.add_argument("--dry-run", action="store_true",
                   help="Show what would change without writing to DB")
    p.add_argument("--promote", action="store_true",
                   help="Promote newly 100%% functions to COMPLETE verdict")
    p.add_argument("--unit", type=str, default=None,
                   help="Only sync functions in units matching this glob")
    p.add_argument("--verbose", "-v", action="store_true",
                   help="Show every update")
    return p.parse_args()


def load_report(report_path: Path) -> dict[str, dict]:
    """Load report.json and return {symbol: info} for all functions with match data."""
    with open(report_path) as f:
        data = json.load(f)

    functions: dict[str, dict] = {}
    for unit in data.get("units", []):
        unit_name = unit["name"]

        # Skip SDK units
        if any(unit_name.startswith(prefix) for prefix in SDK_UNIT_PREFIXES):
            continue

        for fn in unit.get("functions", []):
            pct = fn.get("fuzzy_match_percent")
            if pct is None:
                continue
            symbol = fn["name"]
            size = int(fn.get("size", 0))
            demangled = fn.get("metadata", {}).get("demangled_name")
            functions[symbol] = {
                "unit": unit_name,
                "percent": round(pct, 2),
                "size": size,
                "demangled": demangled,
            }

    return functions


def sync(args: argparse.Namespace) -> None:
    # Optionally rebuild report first
    if args.build:
        print("Building report.json...")
        result = subprocess.run(
            ["ninja", "build/373307D9/report.json"],
            cwd=str(REPO_ROOT),
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            print(f"Build failed:\n{result.stderr[-500:]}", file=sys.stderr)
            sys.exit(1)
        print("  Build complete.")

    if not args.report.exists():
        print(f"Error: Report not found: {args.report}", file=sys.stderr)
        print("Run 'ninja build/373307D9/report.json' or pass --build.", file=sys.stderr)
        sys.exit(1)

    if not args.db.exists():
        print(f"Error: Database not found: {args.db}", file=sys.stderr)
        sys.exit(1)

    # Load report
    print(f"Loading report: {args.report}")
    report_funcs = load_report(args.report)
    print(f"  {len(report_funcs)} functions with match data (excluding SDK)")

    # Connect to DB
    conn = sqlite3.connect(str(args.db))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode = WAL")

    # Build query for DB functions
    query = "SELECT id, symbol, demangled, unit, size, current_percent, verdict FROM functions"
    conditions = []
    params: list = []

    if args.unit:
        # Normalize unit pattern
        pattern = args.unit
        if pattern.startswith("src/"):
            pattern = "default/" + pattern[4:]
        elif not pattern.startswith("default/") and not pattern.startswith("*"):
            pattern = "default/" + pattern
        conditions.append("unit GLOB ?")
        params.append(pattern)

    if conditions:
        query += " WHERE " + " AND ".join(conditions)

    rows = conn.execute(query, params).fetchall()
    db_funcs = {row["symbol"]: dict(row) for row in rows}
    print(f"  {len(db_funcs)} functions in DB" + (f" (filtered: {args.unit})" if args.unit else ""))

    # Match and compute updates
    stats = {
        "pct_updated": 0, "pct_unchanged": 0,
        "improvements": 0, "regressions": 0,
        "size_updated": 0, "demangled_updated": 0,
        "promoted": 0, "not_in_db": 0, "not_in_report": 0,
    }

    pct_updates: list[tuple] = []       # (new_percent, new_percent, function_id)
    field_updates: list[tuple] = []     # (size, demangled, function_id)
    promotions: list[int] = []          # function_ids

    for symbol, report_info in report_funcs.items():
        if symbol not in db_funcs:
            stats["not_in_db"] += 1
            continue

        db_row = db_funcs[symbol]
        new_pct = report_info["percent"]
        old_pct = db_row["current_percent"]

        # Check percent change
        pct_changed = old_pct is None or abs(old_pct - new_pct) >= 0.01
        if pct_changed:
            pct_updates.append((new_pct, new_pct, db_row["id"]))
            stats["pct_updated"] += 1

            if old_pct is not None and new_pct < old_pct:
                stats["regressions"] += 1
                if args.verbose:
                    print(f"  REGRESS {symbol}: {old_pct:.1f}% -> {new_pct:.1f}%")
            elif old_pct is not None and new_pct > old_pct:
                stats["improvements"] += 1
                if args.verbose:
                    print(f"  IMPROVE {symbol}: {old_pct:.1f}% -> {new_pct:.1f}%")
            elif args.verbose:
                print(f"  NEW     {symbol}: -> {new_pct:.1f}%")
        else:
            stats["pct_unchanged"] += 1

        # Check size / demangled changes
        new_size = report_info["size"]
        new_demangled = report_info["demangled"]
        size_changed = new_size and db_row["size"] != new_size
        demangled_changed = new_demangled and db_row["demangled"] != new_demangled

        if size_changed or demangled_changed:
            field_updates.append((
                new_size if size_changed else db_row["size"],
                new_demangled if demangled_changed else db_row["demangled"],
                db_row["id"],
            ))
            if size_changed:
                stats["size_updated"] += 1
            if demangled_changed:
                stats["demangled_updated"] += 1

        # Check for promotion
        if args.promote and new_pct == 100.0 and db_row["verdict"] != "COMPLETE":
            promotions.append(db_row["id"])
            stats["promoted"] += 1

    # Count functions in DB but not in report
    report_symbols = set(report_funcs.keys())
    for symbol in db_funcs:
        if symbol not in report_symbols:
            stats["not_in_report"] += 1

    # Apply updates
    if not args.dry_run:
        if pct_updates:
            conn.executemany(
                """UPDATE functions
                   SET current_percent = ?,
                       best_percent = MAX(COALESCE(best_percent, 0), ?),
                       updated_at = CURRENT_TIMESTAMP
                   WHERE id = ?""",
                pct_updates,
            )
        if field_updates:
            conn.executemany(
                """UPDATE functions
                   SET size = ?, demangled = ?,
                       updated_at = CURRENT_TIMESTAMP
                   WHERE id = ?""",
                field_updates,
            )
        if promotions:
            conn.executemany(
                """UPDATE functions
                   SET verdict = 'COMPLETE',
                       updated_at = CURRENT_TIMESTAMP
                   WHERE id = ?""",
                [(fid,) for fid in promotions],
            )
        conn.commit()

    # Summary
    mode = " (DRY RUN)" if args.dry_run else ""
    print(f"\n--- Sync Results{mode} ---")
    print(f"  Match %% updated: {stats['pct_updated']}")
    print(f"  Match %% unchanged: {stats['pct_unchanged']}")
    print(f"  Improvements:     {stats['improvements']}")
    print(f"  Regressions:      {stats['regressions']}")
    print(f"  Size updated:     {stats['size_updated']}")
    print(f"  Demangled updated:{stats['demangled_updated']}")
    if args.promote:
        print(f"  Promoted:         {stats['promoted']} (-> COMPLETE)")
    print(f"  Not in DB:        {stats['not_in_db']}")
    print(f"  Not in report:    {stats['not_in_report']}")


if __name__ == "__main__":
    sync(parse_args())
