#!/usr/bin/env python3
"""Sync objdiff results from report.json into decomp.db.

Reads the report generated by `ninja build/373307D9/report.json` (which runs
objdiff-cli internally against every object file) and updates every function's
current_percent, size, and demangled name in the database.

Normalized dual-store (roadmap 0.2/0.4):
    report.json function entries carry BOTH `fuzzy_match_percent` (raw, the
    historical `current_percent`) AND `match_percent_normalized` (the canonical
    objdiff scorer that forgives benign relocation/address noise). This script
    stores BOTH: `current_percent` stays fuzzy for continuity, and a new
    `match_percent_normalized` column is filled. `--promote` keys the COMPLETE
    verdict off **normalized == 100**, so the ~206 functions that are 100%
    normalized but <100 fuzzy become promotable.

Demote / freshness (roadmap 0.3/0.7):
    --demote   reverts COMPLETE -> NULL when current_percent < 100 (sync was
               previously promote-only and never demoted, leaving stale-COMPLETE
               rows). Also clears stale `is_stub` flags (is_stub=1 AND
               current_percent >= 100). Symbols present in the DB but absent
               from report.json are reported (never silently mutated).

Usage:
    ninja build/373307D9/report.json && python3 scripts/sync_match_percent.py

Options:
    python3 scripts/sync_match_percent.py --build          # run ninja first
    python3 scripts/sync_match_percent.py --dry-run        # preview only
    python3 scripts/sync_match_percent.py --promote        # promote norm==100 -> COMPLETE
    python3 scripts/sync_match_percent.py --demote         # demote COMPLETE<100 -> NULL, clear stale is_stub
    python3 scripts/sync_match_percent.py --promote-units  # promote 100% units to Matching
    python3 scripts/sync_match_percent.py --unit 'system/char/*'
    python3 scripts/sync_match_percent.py -v               # show every change
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REPORT = REPO_ROOT / "build" / "373307D9" / "report.json"
DEFAULT_DB = REPO_ROOT / "decomp.db"
DEFAULT_OBJECTS = REPO_ROOT / "config" / "373307D9" / "objects.json"

SDK_UNIT_PREFIXES = [
    "default/xdk/",
]
# NOTE: this is the canonical SDK/non-authorable unit-prefix list for the sync
# plane. reconcile_db.py imports it from here; Lane B's authorable-denominator
# work is expected to reconcile this with progress_metrics.py's exclusion set
# (the audit notes default/lib/* may also be non-authorable for byte metrics,
# but for the *report.json function sync* only default/xdk/ functions are
# skipped, matching report-generation scope).


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Sync objdiff report.json into decomp.db",
    )
    p.add_argument("--report", type=Path, default=DEFAULT_REPORT,
                   help=f"Path to report.json (default: {DEFAULT_REPORT})")
    p.add_argument("--db", type=Path, default=DEFAULT_DB,
                   help=f"Path to decomp.db (default: {DEFAULT_DB})")
    p.add_argument("--build", action="store_true",
                   help="Run ninja to rebuild report.json before syncing")
    p.add_argument("--dry-run", action="store_true",
                   help="Show what would change without writing to DB")
    p.add_argument("--promote", action="store_true",
                   help="Promote functions at normalized==100%% to COMPLETE verdict")
    p.add_argument("--demote", action="store_true",
                   help="Demote COMPLETE verdicts whose current_percent<100 to NULL, "
                        "and clear stale is_stub flags (is_stub=1 AND current_percent>=100)")
    p.add_argument("--unit", type=str, default=None,
                   help="Only sync functions in units matching this glob")
    p.add_argument("--promote-units", action="store_true",
                   help="Promote done units (100%% in report OR all COMPLETE/AT_LIMIT in DB) to Matching in objects.json")
    p.add_argument("--verbose", "-v", action="store_true",
                   help="Show every update")
    return p.parse_args()


def load_report(report_path: Path) -> tuple[dict[str, dict], set[str]]:
    """Load report.json and return ({symbol: info}, {units_at_100%}).

    Each function entry in report.json carries BOTH `fuzzy_match_percent` (raw)
    and `match_percent_normalized` (canonical scorer). We capture both so the DB
    can dual-store fuzzy (continuity) and normalized (promotion gate).
    """
    with open(report_path) as f:
        data = json.load(f)

    functions: dict[str, dict] = {}
    units_at_100: set[str] = set()

    for unit in data.get("units", []):
        unit_name = unit["name"]

        # Skip SDK units
        if any(unit_name.startswith(prefix) for prefix in SDK_UNIT_PREFIXES):
            continue

        fns = unit.get("functions", [])
        unit_all_100 = bool(fns) and all(
            f.get("fuzzy_match_percent", 0) == 100.0 for f in fns
        )
        if unit_all_100:
            units_at_100.add(unit_name)

        for fn in fns:
            pct = fn.get("fuzzy_match_percent")
            if pct is None:
                continue
            symbol = fn["name"]
            size = int(fn.get("size", 0))
            demangled = fn.get("metadata", {}).get("demangled_name")
            norm = fn.get("match_percent_normalized")
            functions[symbol] = {
                "unit": unit_name,
                "percent": round(pct, 2),
                "normalized": round(norm, 2) if norm is not None else None,
                "size": size,
                "demangled": demangled,
            }

    return functions, units_at_100


def ensure_normalized_column(conn: sqlite3.Connection, dry_run: bool) -> bool:
    """Ensure the `match_percent_normalized` column exists. Returns True if it
    was just created. A bare ALTER TABLE ADD COLUMN is a metadata-only,
    non-destructive migration. Skipped (but reported) under --dry-run."""
    cols = {row[1] for row in conn.execute("PRAGMA table_info(functions)")}
    if "match_percent_normalized" in cols:
        return False
    if dry_run:
        print("  (dry-run) would ALTER TABLE functions "
              "ADD COLUMN match_percent_normalized REAL")
        return False
    conn.execute("ALTER TABLE functions ADD COLUMN match_percent_normalized REAL")
    conn.commit()
    print("  Migrated: added column match_percent_normalized REAL")
    return True


def find_complete_units(conn: sqlite3.Connection) -> set[str]:
    """Find units where ALL functions are COMPLETE or AT_LIMIT in the DB."""
    # Get all units that have at least one function
    rows = conn.execute("""
        SELECT unit,
               COUNT(*) as total,
               SUM(CASE WHEN verdict IN ('COMPLETE', 'AT_LIMIT') THEN 1 ELSE 0 END) as done
        FROM functions
        WHERE unit NOT LIKE 'default/xdk/%'
        GROUP BY unit
    """).fetchall()
    return {r["unit"] for r in rows if r["total"] > 0 and r["total"] == r["done"]}


def promote_units(
    units_at_100: set[str],
    db_complete_units: set[str],
    dry_run: bool,
    verbose: bool,
) -> int:
    """Promote NonMatching units to Matching in objects.json.

    A unit is eligible if:
    - All functions are 100% in report.json, OR
    - All functions have COMPLETE/AT_LIMIT verdict in the DB
    """
    objects_path = DEFAULT_OBJECTS
    if not objects_path.exists():
        print(f"Warning: objects.json not found at {objects_path}", file=sys.stderr)
        return 0

    with open(objects_path) as f:
        objects = json.load(f)

    eligible = units_at_100 | db_complete_units

    promoted = []
    for section_name, section in objects.items():
        for obj_name, status_val in section.get("objects", {}).items():
            # Get current status
            if isinstance(status_val, dict):
                cur_status = status_val.get("status", "NonMatching")
            else:
                cur_status = status_val

            if cur_status != "NonMatching":
                continue

            # Map object name to report unit name: strip extension, prepend default/
            base = obj_name.rsplit(".", 1)[0]
            report_unit = "default/" + base

            if report_unit not in eligible:
                continue

            # Determine reason for promotion
            in_report = report_unit in units_at_100
            in_db = report_unit in db_complete_units
            if in_report and in_db:
                reason = "100% + all done in DB"
            elif in_report:
                reason = "100% in report"
            else:
                reason = "all COMPLETE/AT_LIMIT in DB"

            # Promote
            if isinstance(status_val, dict):
                section["objects"][obj_name]["status"] = "Matching"
            else:
                section["objects"][obj_name] = "Matching"

            promoted.append(f"{section_name}/{obj_name}")
            if verbose:
                print(f"  PROMOTE {section_name}/{obj_name} -> Matching ({reason})")

    if promoted and not dry_run:
        with open(objects_path, "w") as f:
            json.dump(objects, f, indent=4)
            f.write("\n")

    return len(promoted)


def sync(args: argparse.Namespace) -> None:
    # Optionally rebuild report first
    if args.build:
        print("Building report.json...")
        result = subprocess.run(
            ["ninja", "build/373307D9/report.json"],
            cwd=str(REPO_ROOT),
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            print(f"Build failed:\n{result.stderr[-500:]}", file=sys.stderr)
            sys.exit(1)
        print("  Build complete.")

    if not args.report.exists():
        print(f"Error: Report not found: {args.report}", file=sys.stderr)
        print("Run 'ninja build/373307D9/report.json' or pass --build.", file=sys.stderr)
        sys.exit(1)

    if not args.db.exists():
        print(f"Error: Database not found: {args.db}", file=sys.stderr)
        sys.exit(1)

    # Load report
    print(f"Loading report: {args.report}")
    report_funcs, units_at_100 = load_report(args.report)
    print(f"  {len(report_funcs)} functions with match data (excluding SDK)")
    print(f"  {len(units_at_100)} units at 100%")

    # Connect to DB
    conn = sqlite3.connect(str(args.db))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode = WAL")

    # Ensure dual-store column exists before querying it.
    ensure_normalized_column(conn, args.dry_run)
    has_norm_col = "match_percent_normalized" in {
        row[1] for row in conn.execute("PRAGMA table_info(functions)")
    }

    # Build query for DB functions
    norm_sel = ", match_percent_normalized" if has_norm_col else ""
    query = (
        "SELECT id, symbol, demangled, unit, size, current_percent, verdict, "
        "is_stub, excluded" + norm_sel + " FROM functions"
    )
    conditions = []
    params: list = []

    if args.unit:
        # Normalize unit pattern
        pattern = args.unit
        if pattern.startswith("src/"):
            pattern = "default/" + pattern[4:]
        elif not pattern.startswith("default/") and not pattern.startswith("*"):
            pattern = "default/" + pattern
        conditions.append("unit GLOB ?")
        params.append(pattern)

    if conditions:
        query += " WHERE " + " AND ".join(conditions)

    rows = conn.execute(query, params).fetchall()
    db_funcs = {row["symbol"]: dict(row) for row in rows}
    print(f"  {len(db_funcs)} functions in DB" + (f" (filtered: {args.unit})" if args.unit else ""))

    # Match and compute updates
    stats = {
        "pct_updated": 0, "pct_unchanged": 0,
        "improvements": 0, "regressions": 0,
        "norm_updated": 0,
        "size_updated": 0, "demangled_updated": 0,
        "promoted": 0, "demoted": 0, "stub_cleared": 0,
        "not_in_db": 0, "not_in_report": 0,
    }

    pct_updates: list[tuple] = []       # (new_percent, new_percent, function_id)
    norm_updates: list[tuple] = []      # (normalized, function_id)
    field_updates: list[tuple] = []     # (size, demangled, function_id)
    promotions: list[int] = []          # function_ids
    demotions: list[int] = []           # function_ids (COMPLETE -> NULL)
    stub_clears: list[int] = []         # function_ids (is_stub -> 0)

    for symbol, report_info in report_funcs.items():
        if symbol not in db_funcs:
            stats["not_in_db"] += 1
            continue

        db_row = db_funcs[symbol]
        new_pct = report_info["percent"]
        old_pct = db_row["current_percent"]
        new_norm = report_info["normalized"]

        # Check fuzzy percent change
        pct_changed = old_pct is None or abs(old_pct - new_pct) >= 0.01
        if pct_changed:
            pct_updates.append((new_pct, new_pct, db_row["id"]))
            stats["pct_updated"] += 1

            if old_pct is not None and new_pct < old_pct:
                stats["regressions"] += 1
                if args.verbose:
                    print(f"  REGRESS {symbol}: {old_pct:.1f}% -> {new_pct:.1f}%")
            elif old_pct is not None and new_pct > old_pct:
                stats["improvements"] += 1
                if args.verbose:
                    print(f"  IMPROVE {symbol}: {old_pct:.1f}% -> {new_pct:.1f}%")
            elif args.verbose:
                print(f"  NEW     {symbol}: -> {new_pct:.1f}%")
        else:
            stats["pct_unchanged"] += 1

        # Check normalized change (dual-store)
        if has_norm_col and new_norm is not None:
            old_norm = db_row["match_percent_normalized"] if "match_percent_normalized" in db_row.keys() else None
            if old_norm is None or abs(old_norm - new_norm) >= 0.01:
                norm_updates.append((new_norm, db_row["id"]))
                stats["norm_updated"] += 1

        # Check size / demangled changes
        new_size = report_info["size"]
        new_demangled = report_info["demangled"]
        size_changed = new_size and db_row["size"] != new_size
        demangled_changed = new_demangled and db_row["demangled"] != new_demangled

        if size_changed or demangled_changed:
            field_updates.append((
                new_size if size_changed else db_row["size"],
                new_demangled if demangled_changed else db_row["demangled"],
                db_row["id"],
            ))
            if size_changed:
                stats["size_updated"] += 1
            if demangled_changed:
                stats["demangled_updated"] += 1

        # --- Promotion: keyed off NORMALIZED == 100 (roadmap 0.2/0.4) ---
        if args.promote and new_norm is not None and new_norm >= 100.0 \
                and db_row["verdict"] != "COMPLETE":
            promotions.append(db_row["id"])
            stats["promoted"] += 1
            if args.verbose:
                print(f"  PROMOTE {symbol}: norm {new_norm:.2f} fuzzy {new_pct:.2f} -> COMPLETE")

        # --- Demotion: COMPLETE whose current (fuzzy) < 100 -> NULL (roadmap 0.3) ---
        # Use normalized as the promotion truth, so a COMPLETE row is only demoted
        # when it is BELOW 100 normalized too (avoids churning the 206 fuzzy<100/
        # normalized==100 rows that are legitimately complete).
        if args.demote and db_row["verdict"] == "COMPLETE":
            norm_for_gate = new_norm if new_norm is not None else new_pct
            if norm_for_gate < 100.0:
                demotions.append(db_row["id"])
                stats["demoted"] += 1
                if args.verbose:
                    print(f"  DEMOTE  {symbol}: COMPLETE but norm {norm_for_gate:.2f} -> NULL verdict")

        # --- Stale is_stub clear: is_stub=1 AND current_percent>=100 (roadmap 0.3) ---
        if args.demote and db_row["is_stub"] and new_pct >= 100.0:
            stub_clears.append(db_row["id"])
            stats["stub_cleared"] += 1
            if args.verbose:
                print(f"  UNSTUB  {symbol}: is_stub but {new_pct:.2f}% -> is_stub=0")

    # Count functions in DB but not in report (flag, never mutate).
    # Restrict the "missing" flag to authorable rows (non-excluded, non-xdk,
    # non-ICF-alias) so ICF/link-glue bookkeeping rows don't spam the count.
    report_symbols = set(report_funcs.keys())
    missing_authorable: list[str] = []
    for symbol, db_row in db_funcs.items():
        if symbol not in report_symbols:
            stats["not_in_report"] += 1
            unit = db_row["unit"] or ""
            if (not db_row["excluded"]
                    and not unit.startswith("default/xdk/")
                    and not symbol.startswith("merged_")):
                missing_authorable.append(symbol)

    # Apply updates
    if not args.dry_run:
        if pct_updates:
            conn.executemany(
                """UPDATE functions
                   SET current_percent = ?,
                       best_percent = MAX(COALESCE(best_percent, 0), ?),
                       updated_at = CURRENT_TIMESTAMP
                   WHERE id = ?""",
                pct_updates,
            )
        if norm_updates:
            conn.executemany(
                """UPDATE functions
                   SET match_percent_normalized = ?,
                       updated_at = CURRENT_TIMESTAMP
                   WHERE id = ?""",
                norm_updates,
            )
        if field_updates:
            conn.executemany(
                """UPDATE functions
                   SET size = ?, demangled = ?,
                       updated_at = CURRENT_TIMESTAMP
                   WHERE id = ?""",
                field_updates,
            )
        if promotions:
            conn.executemany(
                """UPDATE functions
                   SET verdict = 'COMPLETE',
                       updated_at = CURRENT_TIMESTAMP
                   WHERE id = ?""",
                [(fid,) for fid in promotions],
            )
        if demotions:
            conn.executemany(
                """UPDATE functions
                   SET verdict = NULL,
                       updated_at = CURRENT_TIMESTAMP
                   WHERE id = ?""",
                [(fid,) for fid in demotions],
            )
        if stub_clears:
            conn.executemany(
                """UPDATE functions
                   SET is_stub = 0,
                       updated_at = CURRENT_TIMESTAMP
                   WHERE id = ?""",
                [(fid,) for fid in stub_clears],
            )
        conn.commit()

    # Summary
    mode = " (DRY RUN)" if args.dry_run else ""
    print(f"\n--- Sync Results{mode} ---")
    print(f"  Fuzzy %% updated:  {stats['pct_updated']}")
    print(f"  Fuzzy %% unchanged:{stats['pct_unchanged']}")
    print(f"  Normalized updated:{stats['norm_updated']}")
    print(f"  Improvements:     {stats['improvements']}")
    print(f"  Regressions:      {stats['regressions']}")
    print(f"  Size updated:     {stats['size_updated']}")
    print(f"  Demangled updated:{stats['demangled_updated']}")
    if args.promote:
        print(f"  Promoted:         {stats['promoted']} (norm==100 -> COMPLETE)")
    if args.demote:
        print(f"  Demoted:          {stats['demoted']} (COMPLETE<100 -> NULL)")
        print(f"  is_stub cleared:  {stats['stub_cleared']} (>=100%% -> is_stub=0)")
    print(f"  Not in DB:        {stats['not_in_db']}")
    print(f"  Not in report:    {stats['not_in_report']}"
          f" ({len(missing_authorable)} authorable)")
    if missing_authorable and args.verbose:
        print("  --- authorable symbols absent from report.json (flagged, not mutated) ---")
        for sym in missing_authorable[:50]:
            print(f"      MISSING {sym}")
        if len(missing_authorable) > 50:
            print(f"      ... and {len(missing_authorable) - 50} more")

    # Promote units in objects.json
    if args.promote_units:
        db_complete_units = find_complete_units(conn)
        print(f"\n--- Unit Promotion ---")
        print(f"  Units at 100%% in report:       {len(units_at_100)}")
        print(f"  Units all done in DB:           {len(db_complete_units)}")
        print(f"  Combined eligible:              {len(units_at_100 | db_complete_units)}")
        num_promoted = promote_units(
            units_at_100, db_complete_units, args.dry_run, args.verbose,
        )
        print(f"  Units promoted:                 {num_promoted} (-> Matching in objects.json)")


if __name__ == "__main__":
    sync(parse_args())
