#!/usr/bin/env python3
"""Refuse to build from a `build.ninja` that was generated for a DIFFERENT tree.

Why this exists
---------------
Every compile edge in this project carries ABSOLUTE paths, and it has to:
`rule msvc` is `cd $in_dir && cl.exe ... /Fo$abs_out $in_win`, because the
compiler must run with its CWD at the source's own directory (the `__FILE__`
basename fix) and an output path relative to that CWD would land in `src/`.
`tools/project.py` therefore bakes `Path.cwd()` into ~6,500 places in
`build.ninja`, and `build.ninja` is gitignored, per-tree, and regenerated by
`configure.py`.

That is correct, and it is also a trap, because the ninja NODE names stay
relative while the COMMANDS are absolute. Copy a built tree without re-running
`configure.py` and ninja decides what is dirty from YOUR files and then compiles
the ORIGIN's sources into the ORIGIN's object tree. Nothing warns; the copy's
own objects never move.

Reproduced 2026-08-26 between two throwaway worktrees, `cp -a --reflink=auto` of
a configured tree, one line prepended to the copy's `src/App.cpp`:

    tree              App.cpp has probe   App.obj mtime     App.obj content
    ---------------   -----------------   ---------------   ---------------
    origin (donor)    no                  MOVED (twice)     REWRITTEN
    copy (built in)   yes                 unchanged         unchanged

...and the probe symbol appears in neither object, because the compile read the
origin's `App.cpp`. So the copy scored a source it had not edited, while
silently overwriting the origin's build dir -- and the origin is, typically, a
scoring lane somebody else is measuring.

`scripts/setup_worktree.sh` and `scripts/configure_existing_worktree.sh` both
re-run `configure.py` inside the new tree and are NOT affected. This guard is
for every other way a tree gets copied.

What this checks
----------------
That the tree root `build.ninja` was generated for is the tree it is sitting in.
The root is read from the `ninja_root` variable `tools/project.py` emits; on a
manifest generated before that variable existed it is RECOVERED from the first
compile edge, by stripping the edge's relative output from its `abs_out`. So the
check works on manifests that predate it, which is the whole population that can
currently be wrong.

Where it is enforced (wired 2026-10-02, lane w10-t)
---------------------------------------------------
Until 2026-10-02 this script was landed UNWIRED (2026-09-13) and said so here:
nothing called it, so a mis-rooted tree still built silently. It is now hung on:

* the `pre-compile` phony, which every compile edge and the PCH edge carry as an
  ORDER-ONLY dependency. Order-only constrains order but never marks an edge
  dirty, so the check runs before the first `cl.exe` at zero rebuild cost, and
  a refusal stops every compile. The edge (`CHECK NINJA ROOT`) is `always` +
  `restat`, like `CHECK SPLIT CURRENT`.
* an implicit input of report.json / report_raw.json / baseline.json, so a
  mis-rooted tree cannot produce a report over objects it never wrote.
* `scripts/orchestrator/patch_guard.ensure_ninja_root()`, called first thing in
  `ensure_patched_tree()` -- BEFORE its `ninja post-compile`, which is the very
  command that would write into the other tree. Raises `ForeignNinjaRootError`,
  a subclass of `UnpatchedTreeError`, so every existing caller refuses.
* `scripts/setup_worktree.sh` and `scripts/configure_existing_worktree.sh`,
  which refuse to hand back a tree that fails it.

The one gap that cannot be closed from inside the manifest: a copy of a tree
whose `build.ninja` was generated BEFORE this wiring has no such edge, so it
will not refuse itself -- `patch_guard` (every MCP/orchestrator build) still
does. Measured incidence when it was landed unwired: 47 of 47 registered dc3
worktree manifests passed on 2026-09-13, against TWO genuinely mis-rooted of
164 on 2026-08-26 (`fix/worktree-relative-ninja`, aa4b8f70d). The population
shrank, not the hazard.

Stamp: `--stamp-out` writes a CONSTANT body. A refusal exits 1 and writes
nothing, so the only verdict a stamp can record is "passed"; making it depend
on the root (as the 2026-08-26 draft did) only made a freshly reflinked
worktree, whose stamp came from main, rewrite it and re-run REPORT once for no
reason.

Exit codes
----------
    0   build.ninja belongs to this tree
    1   it does not, or the state cannot be established (the message says which)
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
from pathlib import Path
from typing import Optional, Tuple


class ForeignNinjaRootError(Exception):
    """build.ninja was generated for a different tree (or cannot be vouched for)."""


# ninja_syntax wraps at 78 columns as ` $\n<indent>`; the space that was broken
# on lives before the `$`, so restoring it is what makes a wrapped absolute path
# readable as one token again.
_CONT = re.compile(r" \$\n\s*")
_VAR_ROOT = re.compile(r"^ninja_root = (.+)$", re.MULTILINE)
_BUILD_LINE = re.compile(r"^build ([^:\n]+): (\S+)", re.MULTILINE)
_ABS_OUT = re.compile(r"^  abs_out = (.+)$", re.MULTILINE)


def _unwrap(text: str) -> str:
    return _CONT.sub(" ", text)


def generated_root(build_ninja: Path) -> Tuple[Path, str]:
    """Return (root the manifest was generated for, how we know).

    Raises ForeignNinjaRootError if the manifest exists but says nothing about
    its root -- an unvouchable manifest is refused, not assumed innocent.
    """
    try:
        text = _unwrap(build_ninja.read_text(encoding="utf-8", errors="replace"))
    except FileNotFoundError:
        raise ForeignNinjaRootError(
            f"no build.ninja at {build_ninja} -- run `python3 configure.py` in this tree"
        )

    m = _VAR_ROOT.search(text)
    if m:
        return Path(m.group(1).strip()), "ninja_root variable"

    # Recovery path for manifests generated before ninja_root existed: pair each
    # `build <relative out>: <rule>` with the `abs_out` of the same edge and
    # strip one from the other. Makes no assumption about the build-dir name.
    for bm in _BUILD_LINE.finditer(text):
        rel = bm.group(1).strip().split(" ")[0]
        am = _ABS_OUT.search(text, bm.end())
        if am is None:
            break
        # Only trust an abs_out that belongs to THIS edge: the next `build`
        # statement must come after it.
        nxt = _BUILD_LINE.search(text, bm.end())
        if nxt is not None and am.start() > nxt.start():
            continue
        absolute = am.group(1).strip()
        suffix = "/" + rel
        if absolute.endswith(suffix):
            return Path(absolute[: -len(suffix)]), f"abs_out of `{rel}`"

    raise ForeignNinjaRootError(
        f"{build_ninja} carries no `ninja_root` and no recoverable `abs_out` -- "
        "cannot establish which tree it was generated for; re-run `python3 configure.py`"
    )


def check(project_dir: Path | str = ".") -> str:
    """Assert `project_dir`'s build.ninja was generated for `project_dir`.

    Returns a one-line note, or raises ForeignNinjaRootError.
    """
    root = Path(project_dir).resolve()
    baked, how = generated_root(root / "build.ninja")
    baked_real = Path(os.path.realpath(baked))
    if baked_real == root:
        return f"build.ninja belongs to this tree ({how})"

    raise ForeignNinjaRootError(
        f"build.ninja was generated for {baked_real}\n"
        f"                  but this tree is {root}\n"
        f"  ({how})\n"
        "  Building here would compile the OTHER tree's sources and OVERWRITE its\n"
        "  objects -- your edits would measure as nothing and its lane would be\n"
        "  silently corrupted.\n"
        "  Fix:  cd " + str(root) + " && python3 configure.py "
        "(or scripts/setup_worktree.sh for a fresh tree)"
    )


def _write_stamp(path: Path, payload: str) -> None:
    """Write only if the content moved, so `restat` keeps downstream edges clean."""
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    body = f"{digest}\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == body:
        return
    path.write_text(body, encoding="utf-8")


def main(argv: Optional[list] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", default=True,
                    help="verify build.ninja belongs to this tree (default)")
    ap.add_argument("--root", default=".", metavar="DIR",
                    help="tree to check (default: cwd)")
    ap.add_argument("--quiet", action="store_true", help="print nothing on success")
    ap.add_argument("--stamp-out", metavar="PATH",
                    help="on success, write a constant stamp here (for a restat ninja edge)")
    args = ap.parse_args(argv)

    try:
        note = check(args.root)
    except ForeignNinjaRootError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.stamp_out:
        # Constant on purpose: see "Stamp:" in the module docstring.
        _write_stamp(Path(args.stamp_out), "build.ninja belongs to the tree it sits in")
    if not args.quiet:
        print(note)
    return 0


if __name__ == "__main__":
    sys.exit(main())
