#!/usr/bin/env python3
"""Refuse to build from a `build.ninja` that was generated for a DIFFERENT tree.

Why this exists
---------------
Every compile edge in this project carries ABSOLUTE paths, and it has to:
`rule msvc` is `cd $in_dir && cl.exe ... /Fo$abs_out $in_win`, because the
compiler must run with its CWD at the source's own directory (the `__FILE__`
basename fix) and an output path relative to that CWD would land in `src/`.
`tools/project.py` therefore bakes `Path.cwd()` into ~6,500 places in
`build.ninja`, and `build.ninja` is gitignored, per-tree, and regenerated by
`configure.py`.

That is correct, and it is also a trap, because the ninja NODE names stay
relative while the COMMANDS are absolute. Copy a built tree without re-running
`configure.py` and ninja decides what is dirty from YOUR files and then compiles
the ORIGIN's sources into the ORIGIN's object tree. Nothing warns; the copy's
own objects never move.

Reproduced 2026-08-26 between two throwaway worktrees, `cp -a --reflink=auto` of
a configured tree, one line prepended to the copy's `src/App.cpp`:

    tree              App.cpp has probe   App.obj mtime     App.obj content
    ---------------   -----------------   ---------------   ---------------
    origin (donor)    no                  MOVED (twice)     REWRITTEN
    copy (built in)   yes                 unchanged         unchanged

...and the probe symbol appears in neither object, because the compile read the
origin's `App.cpp`. So the copy scored a source it had not edited, while
silently overwriting the origin's build dir -- and the origin is, typically, a
scoring lane somebody else is measuring.

`scripts/setup_worktree.sh` and `scripts/configure_existing_worktree.sh` both
re-run `configure.py` inside the new tree and are NOT affected. This guard is
for every other way a tree gets copied.

What this checks
----------------
That the tree root `build.ninja` was generated for is the tree it is sitting in.
The root is read from a `ninja_root` variable if `tools/project.py` emits one;
`tools/project.py` does NOT emit one today (see below), so in practice the root
is always RECOVERED from the first compile edge, by stripping the edge's
relative output from its `abs_out`. That recovery path is the one under test and
the one that matters: it works on every manifest already on disk, which is the
whole population that can currently be wrong.

⚠ NOT WIRED INTO THE BUILD. THIS SCRIPT ENFORCES NOTHING BY ITSELF.
---------------------------------------------------------------------
Nothing calls this. It is a standalone assertion in the same shape as
`verify_split_current.py --check` and `verify_objs_patched.py --check`, but
unlike those two it has NO ninja edge and NO `patch_guard` hook, so a mis-rooted
tree still builds silently. Saying so here rather than describing the wiring it
deserves is deliberate: a correct doc plus an uninstalled hook is zero
enforcement, and this project has been bitten by exactly that shape before.

It was landed unwired on purpose (2026-09-13). The wiring the hazard actually
warrants -- an order-only dep on the `pre-compile` phony every compile edge
already carries, an implicit input on report/baseline, a
`patch_guard.ensure_ninja_root()` before `ninja post-compile`, and asserts in
`setup_worktree.sh` / `configure_existing_worktree.sh` -- touches the compile
graph of a tree that several lanes build concurrently, and the measured
incidence did not justify doing that in a triage lane:

    2026-09-13, this box: 47 of 47 registered dc3 worktree manifests PASS.
    Widening to every directory holding a 373307D9 manifest (31 of them, clones
    included) turns up exactly one refusal, `dc3-decomp-backup` -- and that one
    is the "cannot establish" branch, an unvouchable manifest, not a manifest
    proven to name another tree.

Compare the branch that first wrote this (`fix/worktree-relative-ninja`,
2026-08-26): auditing 164 dc3 worktrees then found TWO genuinely mis-rooted.
The population has since shrunk, not the hazard.

So: run it by hand before trusting a measurement from a tree you did not
configure yourself, and wire it up as its own lane.

Exit codes
----------
    0   build.ninja belongs to this tree
    1   it does not, or the state cannot be established (the message says which)
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
from pathlib import Path
from typing import Optional, Tuple


class ForeignNinjaRootError(Exception):
    """build.ninja was generated for a different tree (or cannot be vouched for)."""


# ninja_syntax wraps at 78 columns as ` $\n<indent>`; the space that was broken
# on lives before the `$`, so restoring it is what makes a wrapped absolute path
# readable as one token again.
_CONT = re.compile(r" \$\n\s*")
_VAR_ROOT = re.compile(r"^ninja_root = (.+)$", re.MULTILINE)
_BUILD_LINE = re.compile(r"^build ([^:\n]+): (\S+)", re.MULTILINE)
_ABS_OUT = re.compile(r"^  abs_out = (.+)$", re.MULTILINE)


def _unwrap(text: str) -> str:
    return _CONT.sub(" ", text)


def generated_root(build_ninja: Path) -> Tuple[Path, str]:
    """Return (root the manifest was generated for, how we know).

    Raises ForeignNinjaRootError if the manifest exists but says nothing about
    its root -- an unvouchable manifest is refused, not assumed innocent.
    """
    try:
        text = _unwrap(build_ninja.read_text(encoding="utf-8", errors="replace"))
    except FileNotFoundError:
        raise ForeignNinjaRootError(
            f"no build.ninja at {build_ninja} -- run `python3 configure.py` in this tree"
        )

    m = _VAR_ROOT.search(text)
    if m:
        return Path(m.group(1).strip()), "ninja_root variable"

    # Recovery path for manifests generated before ninja_root existed: pair each
    # `build <relative out>: <rule>` with the `abs_out` of the same edge and
    # strip one from the other. Makes no assumption about the build-dir name.
    for bm in _BUILD_LINE.finditer(text):
        rel = bm.group(1).strip().split(" ")[0]
        am = _ABS_OUT.search(text, bm.end())
        if am is None:
            break
        # Only trust an abs_out that belongs to THIS edge: the next `build`
        # statement must come after it.
        nxt = _BUILD_LINE.search(text, bm.end())
        if nxt is not None and am.start() > nxt.start():
            continue
        absolute = am.group(1).strip()
        suffix = "/" + rel
        if absolute.endswith(suffix):
            return Path(absolute[: -len(suffix)]), f"abs_out of `{rel}`"

    raise ForeignNinjaRootError(
        f"{build_ninja} carries no `ninja_root` and no recoverable `abs_out` -- "
        "cannot establish which tree it was generated for; re-run `python3 configure.py`"
    )


def check(project_dir: Path | str = ".") -> str:
    """Assert `project_dir`'s build.ninja was generated for `project_dir`.

    Returns a one-line note, or raises ForeignNinjaRootError.
    """
    root = Path(project_dir).resolve()
    baked, how = generated_root(root / "build.ninja")
    baked_real = Path(os.path.realpath(baked))
    if baked_real == root:
        return f"build.ninja belongs to this tree ({how})"

    raise ForeignNinjaRootError(
        f"build.ninja was generated for {baked_real}\n"
        f"                  but this tree is {root}\n"
        f"  ({how})\n"
        "  Building here would compile the OTHER tree's sources and OVERWRITE its\n"
        "  objects -- your edits would measure as nothing and its lane would be\n"
        "  silently corrupted.\n"
        "  Fix:  cd " + str(root) + " && python3 configure.py "
        "(or scripts/setup_worktree.sh for a fresh tree)"
    )


def _write_stamp(path: Path, payload: str) -> None:
    """Write only if the content moved, so `restat` keeps downstream edges clean."""
    digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    body = f"{digest}\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == body:
        return
    path.write_text(body, encoding="utf-8")


def main(argv: Optional[list] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", default=True,
                    help="verify build.ninja belongs to this tree (default)")
    ap.add_argument("--root", default=".", metavar="DIR",
                    help="tree to check (default: cwd)")
    ap.add_argument("--quiet", action="store_true", help="print nothing on success")
    ap.add_argument("--stamp-out", metavar="PATH",
                    help="write a digest of the verdict here (for a restat ninja edge)")
    args = ap.parse_args(argv)

    try:
        note = check(args.root)
    except ForeignNinjaRootError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.stamp_out:
        _write_stamp(Path(args.stamp_out), str(Path(args.root).resolve()))
    if not args.quiet:
        print(note)
    return 0


if __name__ == "__main__":
    sys.exit(main())
