export const meta = {
  name: 'loop-build',
  description: 'Build the inverse-compilation loop: 17 tasks (deduction/Z3/ML/egraph/integration) in 4 dependency-ordered waves of parallel Opus build agents, disjoint file ownership',
  phases: [{ title: 'Wave1' }, { title: 'Wave2' }, { title: 'Wave3' }, { title: 'Wave4' }],
}

const DS = '/home/free/code/milohax/decomp-synth'
const RC = DS + '/docs/plans/reverse-compilation'
const COMMON = `You are an Opus build engineer implementing ONE task of decomp-synth's production inverse-compilation LOOP. READ FIRST: ${RC}/LOOP_ARCHITECTURE.md (your component's full spec — authoritative), ${DS}/docs/architecture/INVERSE_COMPILATION.md, and ${RC}/data/INDEX.md (the X1-X9 data your design rests on). decomp-synth is pip-installed (import decomp_synth); use python3 (= the venv with sklearn 1.7.2 / z3 4.16 / numpy / scipy). NEVER git stash/commit/revert. Build A+ quality: typed, documented, argparse CLIs where applicable. CRITICAL: create/edit ONLY your owned files — other build agents own other files THIS wave; do not touch theirs. Your dependencies were built in earlier waves THIS run — import them. ACCEPTANCE (self-validate before returning): import-check every module you wrote; run any self-test you add; if your task says to validate against fixtures.db / a harness / a metric, actually RUN it and report the number. If something is underspecified, make the call the architecture doc implies and note it.`

const SCHEMA = { type:'object', additionalProperties:false, properties:{ id:{type:'string'}, files_written:{type:'array',items:{type:'string'}}, self_test_passed:{type:'boolean'}, validated_metric:{type:'string'}, notes:{type:'string'}, done:{type:'boolean'} }, required:['id','files_written','self_test_passed','done'] }

function build(t){ return `${COMMON}\n\nTASK ${t.id}: ${t.title}\n\nWHAT TO BUILD:\n${t.what}\n\nYOU OWN (create/edit ONLY these): ${t.owns}\nDEPENDENCIES (built earlier this run — import them): ${t.dep||'(none)'}\nLENS: ${t.lens}\n\nReturn the StructuredOutput.` }

const G1 = [
  { id:"T-INT1", title:"Shared serde record module", what:"Lift the records currently implicit in closing_sweep.py into one named, serde-stable module: FrontierRecord, RootCauseRecord, MoveContract, OracleDescriptor, OracleResult (tagged union), FloorProof, OrbitCandidate, AttemptRecord (+ OutcomeClass enum), FrontierVerdict, and the shared MismatchClass enum. Python @dataclass now; field-for-field mirror closing_sweep.Target/CloseResult and decomp_synth.types.Diagnosis so existing code keeps working. JSONL/SQLite (de)serializers. This is the data boundary every other task imports.", owns:"decomp_synth/revcomp_records.py", dep:"", lens:"integration" },
  { id:"T-D1", title:"Reaching-definitions Feeds variant in the fixpoint", what:"Add the ~6-line reaching-def variant of solve() (connect each Use to the LATEST Def before it, not all earlier Defs) behind a feeds_algo flag, defaulting to all_pairs until Q1 fixture validation flips it. Keep the X9-proven all_pairs path verbatim as the alternative. Add a tiny validate-against-fixtures.db harness entry that records which variant lands RootMismatch on the known induced perturbation more often. Zero compiles.", owns:"tools/revcomp/fixpoint_provenance.py", dep:"", lens:"deduction" },
  { id:"T-D2", title:"MoveCanAffect declarative table", what:"New dict MoveCanAffect(move, mismatch_class) \u2014 the inverse of routes_from_diagnosis's ad-hoc dispatch. Seed entries from closing_sweep.routes_from_diagnosis implications. CRUCIAL: encode the X2 fix-family ceiling as EXPLICIT non-membership \u2014 NO opcode-diff move is eligible for statement_reorder/variable_extraction symptom shapes (recall 0/26, 0/9). Provide eligible_moves(class)->list and rejected_moves(class)->list[(move,reason)]. Validate against fixtures.db (induced family known). Pure, zero compiles.", owns:"decomp_synth/move_can_affect.py", dep:"", lens:"deduction" },
  { id:"T-D6", title:"fpr_homes + init_deps fact extraction (closes X5 fact-supply gap)", what:"Extend fact_extract.py to emit fpr_homes (var -> callee-saved FPR home recovered from objdiff/typed_args) and init_deps (v reads w) alongside the existing Def/Use/Mismatch. This closes the X5 section-5 gap (DC3 has_float* flags unpopulated) so the constraint-lens FprDeclOrderOracle can return SOLVED/UNSAT instead of MISSING_FACTS. Keep the existing conservative def/use model intact; add the FPR-home + initializer-dependency recovery as additive output. Zero compiles.", owns:"tools/revcomp/fact_extract.py", dep:"", lens:"deduction" },
  { id:"T-ML1", title:"GBT/logistic/isotonic backend protocol", what:"fit(X,y,weights)/predict_proba(X) protocol with sklearn as the DEFAULT backend (HistGradientBoostingClassifier + CalibratedClassifierCV \u2014 sklearn 1.7.2 is installed) AND a numpy-only histogram-GBT + logistic + isotonic-PAV fallback selectable via --backend numpy. The two must be interchangeable and A/B-able. numpy 2.2.6 + scipy 1.15.3 are present. ~300 LOC.", owns:"tools/revcomp/gbt.py", dep:"", lens:"ml" },
  { id:"T-ML2", title:"Rich-dataset fuser -> learn.db + dense .npz", what:"Fuse the 6 history sources (pattern_runs 142K, climb_variant 86K, decomp.db functions, historical_fixtures validated 154 + fixtures 1336, fixtures.db 68) into a NEW rebuildable learn.db::attempts table + a dense .npz (X, y_* multi-head labels, groups=symbol, weights, feature_names). CLI build/refresh/stats. Backfill ALL labels from cached columns + the compile-free L2 fixpoint over score_cache (775K rows) \u2014 ZERO new compiles. Carry flags_are_current + --sub100 cut for the cleared-flag caveat. Reuse mine_attempts SYMPTOM_FLAGS/wilson, revfix induced-class/noise counters, eval_classifier.reconstruct_diagnosis. learn.db lives next to historical_fixtures.db, never mutates a provenance plane. ~400 LOC.", owns:"tools/revcomp/revcomp_dataset.py", dep:"", lens:"ml" }
]
const G2 = [
  { id:"T-D3", title:"root_cause.py \u2014 RootCauseRecord assembly engine", what:"The deduction lens's home. Import fixpoint_provenance.solve, fact_extract.extract_facts, classifier.classify_mismatches, MoveCanAffect. Per ROOT: run solve() (record feeds_algo used), localize the first divergence + collateral set, call the classifier on a ROOT-SCOPED Diagnosis to get mismatch_class, look up eligible/rejected moves via MoveCanAffect, compute frontier_kind (structural arm: known_no_local_move / missing_move / compiler_phase_frontier / semantic_skeleton_suspect / tooling_frontier / attribution_frontier), and emit one RootCauseRecord per root ordered by downstream_count. Pure, zero compiles. ~200 LOC. Provide route_from_root_cause(records) the orchestrator will call.", owns:"tools/revcomp/root_cause.py", dep:"T-INT1, T-D1, T-D2, T-D6", lens:"deduction" },
  { id:"T-C1", title:"OracleRegistry + typed records + dispatch", what:"New decomp_synth/oracles/ module. Define the DecisionOracle Protocol (descriptor / applicability(ctx,root)->NOT_APPLICABLE|MISSING_FACTS|APPLICABLE(score) / consult(ctx,root)->OracleResult), the OracleRegistry (register + consult dispatch keyed on observes \u2229 root.mismatch_class), and the consult() loop the planner calls. OracleDescriptor/OracleResult/FloorProof come from T-INT1; this owns the registry mechanics + the applicability gating. ~250 LOC.", owns:"decomp_synth/oracles/__init__.py, decomp_synth/oracles/registry.py", dep:"T-INT1", lens:"constraint" },
  { id:"T-C2", title:"BranchFusionLegality \u2014 8 new neutrality Moves (do first, cheapest oracle)", what:"Extend neutrality_oracle._build_moves() with the 8 one-Move extensions X6 already lists: branch_polarity, clamp_to_ternary, max_to_conditional, ternary_swap, condition_arithmetic, bool_cast, bit_test_bool, u8_to_unsigned_long. Reuse verify() machinery verbatim; certify which branch-rewrite edge is behaviour-neutral (neutral for pure conditions, refuted for side-effecting). Widens the X6 gate from 15/23 to 23/23 of the semantic-bet family. Add self-tests. ~80 LOC. Independent leaf edit \u2014 no other task touches this file in this wave.", owns:"tools/revcomp/neutrality_oracle.py", dep:"", lens:"constraint" },
  { id:"T-ML3", title:"move_synthesis.py \u2014 diff->contract + k-NN solved-pair retrieval", what:"Parse historical diff_text into the move-contract vocabulary (reuse the X2b 9-way edit_kind buckets) and build a k-NN retrieval index over the ~650 clean solved before-states, surfacing moves that ACTUALLY closed similar functions (deployment-distribution correction). Labeling + retrieval ONLY, never generative (X7: no egg). Prior-shaping, never a hard route (51% of befores don't recompile). Reuse historical_fixtures.db fixtures table. ~250 LOC.", owns:"tools/revcomp/move_synthesis.py", dep:"T-ML2", lens:"ml" },
  { id:"T-ML4", title:"move_ranker.py \u2014 multi-head trainer + prior/weather CLI", what:"Train the multi-head models on the .npz: P(win|ctx,move) [primary], P(no_asm) [suppressor], P(reaches_100) [floor vote], E[best_delta] [tie-break], P(build_failed) [demote fragile], P(symptom-label-wrong) [route to re-diagnosis]. Never one win-rate (FLAG_PRECISION). Isotonic-calibrated, grouped-CV by symbol, deployment-weighted toward the X2b mix. CLI train/eval(AUC+Brier+ECE+reliability)/prior(emit a seed_from_prior-shaped {move:{wilson:p}} dict for a FeatureContext, scaled to the bandit's Wilson range)/weather. Pure at inference. Serialize to ranker.npz. --no-ranker falls back to mine_attempts population prior. ~350 LOC.", owns:"tools/revcomp/move_ranker.py", dep:"T-ML1, T-ML2", lens:"ml" },
  { id:"T-O1", title:"OrbitGenerator library + OrbitCandidate site/region", what:"Refactor the X7 tool into a reusable in-loop library: split orbit.py into decomp_synth/orbit/generator.py (build_orbit + OrbitForm + _RULES), decomp_synth/orbit/cost.py (CostModel, the X1 prior ranker), decomp_synth/orbit/rules/ (per-family _rule_* modules). Consume the live X2 Diagnosis to scope the region (replace _active_symptom flag-derivation). Emit OrbitCandidate records (from T-INT1) carrying the new site/region fields + rule_tags + x6_labels + pre_bets + generator='dag'. Keep tools/revcomp/orbit.py as the A/B CLI importing the library. ~150 LOC.", owns:"decomp_synth/orbit/__init__.py, decomp_synth/orbit/generator.py, decomp_synth/orbit/cost.py, decomp_synth/orbit/rules/__init__.py, decomp_synth/orbit/rules/cmp_branch.py", dep:"T-INT1", lens:"egraph" }
]
const G3 = [
  { id:"T-C3", title:"Oracle adapters: FprDeclOrder + Neutrality + CommutativeNegative", what:"Thin adapters from the registry interface to the built tools. fpr_decl_order.py: wrap fpr_solver.solve()/FprInversionProblem/_make_recipe, build the problem from RootCauseRecord + fpr_homes/init_deps (T-D6), SAT->SOLVED_EDIT(confirm_budget=1), UNSAT->FLOOR_PROOF(minimal core + signature), volatile-FPR residual->ADVISORY compiler_phase_frontier. neutrality.py: wrap neutrality_oracle.verify()/gate_label + the conservative _build_oracle_gate reading, emit GATE_VERDICT only. commutative_negative.py: ~40 LOC empirical SUPPRESSION of the plain 2-term commutative operand swap (Stream3 backend floor), NO z3. Register all three.", owns:"decomp_synth/oracles/fpr_decl_order.py, decomp_synth/oracles/neutrality.py, decomp_synth/oracles/commutative_negative.py", dep:"T-C1, T-D6", lens:"constraint" },
  { id:"T-O3", title:"X7b egg-decision gate (pre-registered byte/bit A/B)", what:"Run the EXACT X7 A/B harness (orbit.py ab + CostModel + x6_gate + Scorer + _egg_verdict's three-way 0.25 verdict) on the BYTE/BIT family (ByteGrinder-style X3b targets). Add the byte/bit _rule_* family (mask/trunc/zext/shift-mask/int-abs) + a require_flag for the byte/bit symptom. Apply the IDENTICAL >=25%-composition-helps gate. Adopt egg ONLY if it clears; else byte/bit rules ride the bounded DAG. Output the verdict to data/X7b_byte_bit_orbit.md. Zero new infra. ~1 day. Owns a NEW rules module + the experiment doc, does NOT edit the wave-2 orbit library files.", owns:"decomp_synth/orbit/rules/byte_bit.py, docs/plans/reverse-compilation/data/X7b_byte_bit_orbit.md", dep:"T-O1", lens:"egraph" },
  { id:"T-INT3", title:"Plane-B schema extension + AttemptRecord logging + X1 re-mine trigger", what:"Extend the permuter_cache.db pattern_runs schema (EXTEND never replace \u2014 the irreplaceable 142K asset) with outcome_class, source_hash, eligible_because, region, site columns + a migration. Provide log_attempt(record) writing one AttemptRecord per scored variant (with outcome_class, not delta>0; was_new_best for the bandit). Add a re-mine trigger that re-derives the X1 prior from the loop's own AttemptRecords (corrects survivorship bias by logging losses). Owns a new logging helper module + the migration SQL; mine_attempts gets a re-mine entrypoint.", owns:"tools/revcomp/attempt_log.py, tools/revcomp/migrations/001_attempt_record_columns.sql", dep:"T-INT1", lens:"integration" }
]
const G4 = [
  { id:"T-INT2", title:"Loop orchestrator: run_loop.py + closing_sweep rewiring", what:"The Layer-4 planner. NEW tools/revcomp/run_loop.py: the G->B->S->R->O->A->E per-function PLAN() state machine, banded sweep over the X3b worklist, global/per-band budget split, <=6 parallel workers, incremental FrontierVerdict + AttemptRecord streaming, resumable via the de-salted cache. REWIRE closing_sweep.py: replace routes_from_diagnosis(diag) with route_from_root_cause(records) (T-D3), replace _build_oracle_gate with OracleRegistry.consult (T-C1/T-C3), seed BudgetAllocator from the ML ranker prior (T-ML4, --no-ranker fallback to population prior), gate stage O on cmp_branch roots via OrbitGenerator (T-O1), log via attempt_log (T-INT3). Single owner of closing_sweep.py to avoid concurrent edits. SOLO TASK.", owns:"tools/revcomp/run_loop.py, tools/revcomp/closing_sweep.py", dep:"T-D3, T-C1, T-C2, T-C3, T-ML4, T-O1, T-INT3", lens:"integration" },
  { id:"T-C4", title:"Validation gates: Q1 Feeds variant + X8 ranker-vs-prior replay + X7b verdict review", what:"Run the three cheap pre-registered validations that gate defaults, all zero-or-few compiles: (Q1) which Feeds variant (reaching_def vs all_pairs) lands RootMismatch on the known induced perturbation more often across fixtures.db -> set the fixpoint default. (ML) replay the X8 robustness sim drawing true-best from the model's per-function ranking vs the population ranking; if the model doesn't concentrate true-best at rank 0-1 more than the population prior, ship the population prior and keep only the suppressor heads. (Orbit) review the T-O3 X7b verdict and record the egg adopt/defer decision. Write findings to data/.", owns:"docs/plans/reverse-compilation/data/validation_gates.md", dep:"T-D1, T-ML4, T-O3", lens:"integration" }
]

const results = {}
phase('Wave1')
log('Wave1: building ' + G1.length + ' tasks (' + G1.map(t=>t.id).join(', ') + ')')
results.wave1 = (await parallel(G1.map(t => () => agent(build(t), { label:'build:'+t.id, phase:'Wave1', schema:SCHEMA })))).filter(Boolean)
phase('Wave2')
log('Wave2: building ' + G2.length + ' tasks (' + G2.map(t=>t.id).join(', ') + ')')
results.wave2 = (await parallel(G2.map(t => () => agent(build(t), { label:'build:'+t.id, phase:'Wave2', schema:SCHEMA })))).filter(Boolean)
phase('Wave3')
log('Wave3: building ' + G3.length + ' tasks (' + G3.map(t=>t.id).join(', ') + ')')
results.wave3 = (await parallel(G3.map(t => () => agent(build(t), { label:'build:'+t.id, phase:'Wave3', schema:SCHEMA })))).filter(Boolean)
phase('Wave4')
log('Wave4: building ' + G4.length + ' tasks (' + G4.map(t=>t.id).join(', ') + ')')
results.wave4 = (await parallel(G4.map(t => () => agent(build(t), { label:'build:'+t.id, phase:'Wave4', schema:SCHEMA })))).filter(Boolean)
return results