"""Intelligent patch merger agent for concurrent decomp orchestration.

Replaces naive `git apply` with a queued, Claude-powered merger that
understands C++ code and can apply patches correctly even when the base
has drifted from concurrent agent edits.
"""

import asyncio
import json
import logging
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from .database import get_connection
from .types import AgentRunConfig, AgentRunResult, MERGER_TOOLS

logger = logging.getLogger("decomp_orchestrator")


MERGER_PROMPT_TEMPLATE = """\
You are a patch merger for a C++ decompilation project (Xbox 360 / PowerPC).
Your job is to apply queued patches to the main repository. Each patch was
generated by an agent working in an isolated git worktree.

## Instructions

For each patch in the manifest:
1. Read the patch file to understand what changes were made
2. Read the current state of the target file(s) in the repo
3. Apply the changes using Edit (preferred) or Write
   - If the patch applies cleanly to the current file state, apply it directly
   - If the file has changed since the patch was generated (context drift from
     concurrent edits), use your understanding of the C++ code to merge
     correctly — the patch's INTENT matters more than exact context lines
   - Common drift: other functions in the same file were modified by another
     agent. Your patch's target function should still be identifiable.
4. After applying each patch, call mark_patch_result with the result
5. After all patches are applied, run `ninja` to verify the build succeeds
6. If the build fails after a patch, investigate:
   - If the failure is in the patched file, revert the change and mark failed
   - If the failure is unrelated, it may be a pre-existing issue — continue

## Patch Manifest

{manifest_json}

Patch files are at: {patch_dir}

Each file is named `{{queue_id}}.patch` and contains a standard git diff.

## Important Rules
- Apply patches in the order listed (highest priority first)
- Do NOT modify files beyond what the patches specify
- Do NOT add comments, docstrings, or other modifications
- If a patch is for a function that no longer exists or has been completely
  rewritten, mark it as 'skipped' with a reason
- After all patches, run `ninja` one final time to verify everything builds
"""


class MergerAgent:
    """Manages a single merger agent that applies queued patches to main repo.

    Only one merger agent runs at a time. Patches are queued in the database
    and claimed in batches. The merger applies them using Claude's Edit tool
    for intelligent conflict resolution.
    """

    def __init__(
        self,
        main_repo: Path,
        db_path: str,
        agent_runner: Any,  # AgentRunner instance
        max_batch: int = 5,
    ):
        self.main_repo = Path(main_repo).resolve()
        self.db_path = db_path
        self.agent_runner = agent_runner
        self.max_batch = max_batch
        self._running = False
        self._task: Optional[asyncio.Task] = None
        self._session_counter = 0

    def enqueue(
        self,
        attempt_id: int,
        function_id: int,
        symbol: str,
        demangled: Optional[str],
        unit: Optional[str],
        patch: str,
        start_percent: float,
        end_percent: float,
    ) -> int:
        """Add patch to queue. Returns queue ID.

        Priority: patches with progress improvement get higher priority.
        """
        if not patch or not patch.strip():
            return -1

        # Higher priority for actual progress improvements
        improvement = (end_percent or 0) - (start_percent or 0)
        priority = 10 if improvement > 0 else 0

        conn = get_connection(self.db_path)
        try:
            cursor = conn.execute(
                """INSERT INTO patch_queue
                   (attempt_id, function_id, symbol, demangled, unit,
                    patch, priority, start_percent, end_percent)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    attempt_id,
                    function_id,
                    symbol,
                    demangled,
                    unit,
                    patch,
                    priority,
                    start_percent,
                    end_percent,
                ),
            )
            conn.commit()
            queue_id = cursor.lastrowid
            logger.debug(f"Enqueued patch #{queue_id} for {demangled or symbol} "
                         f"({start_percent:.1f}% -> {end_percent:.1f}%)")
            return queue_id
        finally:
            conn.close()

    def _count_pending(self) -> int:
        """Count pending patches in queue."""
        conn = get_connection(self.db_path)
        try:
            row = conn.execute(
                "SELECT COUNT(*) FROM patch_queue WHERE status = 'pending'"
            ).fetchone()
            return row[0]
        finally:
            conn.close()

    async def maybe_spawn(self) -> bool:
        """Spawn merger agent if not already running and queue has work.

        Returns True if a new merger was spawned.
        """
        if self._running:
            return False

        pending = self._count_pending()
        if pending == 0:
            return False

        self._running = True
        self._task = asyncio.create_task(self._run_merger())
        logger.info(f"Spawned merger agent ({pending} pending patches)")
        return True

    async def _run_merger(self):
        """Execute the merger agent loop."""
        self._session_counter += 1
        session_id = f"merger-{datetime.now().strftime('%Y%m%d_%H%M%S')}-{self._session_counter}"
        patch_dir = None

        try:
            # Claim up to max_batch patches
            patches = self._claim_batch(session_id)
            if not patches:
                logger.debug("Merger: no patches to claim")
                return

            logger.info(f"Merger {session_id}: claimed {len(patches)} patches")

            # Write patch files to temp directory
            patch_dir = Path(tempfile.mkdtemp(prefix="merger-patches-"))
            manifest = self._write_patch_files(patches, patch_dir)

            # Build the merger prompt
            prompt = MERGER_PROMPT_TEMPLATE.format(
                manifest_json=json.dumps(manifest, indent=2),
                patch_dir=str(patch_dir),
            )

            # Run Claude agent in main repo (NOT a worktree)
            config = AgentRunConfig(
                session_id=session_id,
                worktree=self.main_repo,
                prompt=prompt,
                model="sonnet",
                max_turns=200,
                allowed_tools=list(MERGER_TOOLS),
            )

            result = await self.agent_runner.run(config)

            # Check which patches were marked by the agent via MCP tool
            # Any patches still 'in_progress' after agent exits → failed
            self._finalize_unclaimed(session_id)

            logger.info(
                f"Merger {session_id} complete: "
                f"exit_code={result.exit_code}, status={result.status}"
            )

        except Exception as e:
            logger.error(f"Merger {session_id} failed: {e}", exc_info=True)
            # Mark all in_progress patches from this session as failed
            self._fail_session(session_id, str(e))
        finally:
            self._running = False
            # Clean up temp files
            if patch_dir and patch_dir.exists():
                import shutil
                shutil.rmtree(patch_dir, ignore_errors=True)

            # Check if more patches arrived while we were running.
            # Defer respawn to let the SDK's async generators fully close
            # before starting a new agent session.
            remaining = self._count_pending()
            if remaining > 0:
                logger.info(f"Merger: {remaining} more patches pending, respawning after cleanup delay")
                asyncio.get_event_loop().call_later(
                    2.0, self._deferred_respawn
                )

    def _deferred_respawn(self):
        """Respawn merger after a delay. Called via call_later to avoid
        conflicting with the previous SDK session's async generator cleanup."""
        if self._running:
            return
        pending = self._count_pending()
        if pending == 0:
            return
        self._running = True
        self._task = asyncio.create_task(self._run_merger())
        logger.info(f"Merger respawned for {pending} pending patches")

    def _claim_batch(self, session_id: str) -> list[dict]:
        """Claim up to max_batch pending patches. Returns list of patch dicts."""
        conn = get_connection(self.db_path)
        try:
            # Select highest priority pending patches
            rows = conn.execute(
                """SELECT id, attempt_id, function_id, symbol, demangled, unit,
                          patch, priority, start_percent, end_percent
                   FROM patch_queue
                   WHERE status = 'pending'
                   ORDER BY priority DESC, id ASC
                   LIMIT ?""",
                (self.max_batch,),
            ).fetchall()

            if not rows:
                return []

            patches = []
            for row in rows:
                patch = dict(row)
                patches.append(patch)
                # Mark as in_progress
                conn.execute(
                    """UPDATE patch_queue
                       SET status = 'in_progress', merger_session_id = ?
                       WHERE id = ?""",
                    (session_id, row["id"]),
                )

            conn.commit()
            return patches
        finally:
            conn.close()

    def _write_patch_files(self, patches: list[dict], patch_dir: Path) -> list[dict]:
        """Write patch contents to individual files. Returns manifest entries."""
        manifest = []
        for p in patches:
            patch_file = patch_dir / f"{p['id']}.patch"
            patch_file.write_text(p["patch"])

            # Extract affected files from the patch
            affected_files = []
            for line in p["patch"].split("\n"):
                if line.startswith("diff --git a/"):
                    # Extract b/ path
                    parts = line.split(" b/")
                    if len(parts) == 2:
                        affected_files.append(parts[1])

            manifest.append({
                "queue_id": p["id"],
                "symbol": p["symbol"],
                "demangled": p.get("demangled"),
                "unit": p.get("unit"),
                "patch_file": str(patch_file),
                "affected_files": affected_files,
                "start_percent": p.get("start_percent"),
                "end_percent": p.get("end_percent"),
                "priority": p.get("priority", 0),
            })

        return manifest

    def _finalize_unclaimed(self, session_id: str):
        """Mark any patches still in_progress from this session as failed."""
        conn = get_connection(self.db_path)
        try:
            conn.execute(
                """UPDATE patch_queue
                   SET status = 'failed',
                       failure_reason = 'Agent exited without marking result'
                   WHERE merger_session_id = ? AND status = 'in_progress'""",
                (session_id,),
            )
            conn.commit()
        finally:
            conn.close()

    def _fail_session(self, session_id: str, reason: str):
        """Mark all in_progress patches from this session as failed."""
        conn = get_connection(self.db_path)
        try:
            conn.execute(
                """UPDATE patch_queue
                   SET status = 'failed',
                       failure_reason = ?
                   WHERE merger_session_id = ? AND status = 'in_progress'""",
                (reason, session_id),
            )
            conn.commit()
        finally:
            conn.close()

    async def drain(self):
        """Wait for running merger to complete (for graceful shutdown)."""
        if self._task and not self._task.done():
            logger.info("Draining merger agent...")
            try:
                await asyncio.wait_for(self._task, timeout=300)
            except asyncio.TimeoutError:
                logger.warning("Merger drain timed out after 5 minutes")
                self._task.cancel()
                try:
                    await self._task
                except asyncio.CancelledError:
                    pass

    def status(self) -> dict:
        """Get merger status for display."""
        conn = get_connection(self.db_path)
        try:
            counts = {}
            for status in ("pending", "in_progress", "applied", "failed", "skipped"):
                row = conn.execute(
                    "SELECT COUNT(*) FROM patch_queue WHERE status = ?",
                    (status,),
                ).fetchone()
                counts[status] = row[0]
            counts["running"] = self._running
            return counts
        finally:
            conn.close()


# --- Database helper for MCP tool ---

def mark_patch_result(
    queue_id: int,
    status: str,
    reason: str = "",
    db_path: str = "decomp.db",
) -> dict:
    """Mark a queued patch as applied, failed, or skipped.

    Called by the merger agent via MCP tool.

    Args:
        queue_id: Patch queue ID
        status: 'applied', 'failed', or 'skipped'
        reason: Explanation (required if failed/skipped)
        db_path: Database path

    Returns:
        Result dict with success status
    """
    if status not in ("applied", "failed", "skipped"):
        return {"success": False, "error": f"Invalid status: {status}. Must be applied, failed, or skipped."}

    conn = get_connection(db_path)
    try:
        # Verify the patch exists and is in_progress
        row = conn.execute(
            "SELECT id, symbol, status FROM patch_queue WHERE id = ?",
            (queue_id,),
        ).fetchone()

        if not row:
            return {"success": False, "error": f"Patch queue ID {queue_id} not found"}

        if row["status"] != "in_progress":
            return {
                "success": False,
                "error": f"Patch {queue_id} is '{row['status']}', expected 'in_progress'",
            }

        conn.execute(
            """UPDATE patch_queue
               SET status = ?,
                   failure_reason = CASE WHEN ? != '' THEN ? ELSE NULL END,
                   applied_at = CASE WHEN ? = 'applied' THEN CURRENT_TIMESTAMP ELSE NULL END
               WHERE id = ?""",
            (status, reason, reason, status, queue_id),
        )
        conn.commit()

        logger.info(f"Patch #{queue_id} ({row['symbol']}): {status}"
                     + (f" — {reason}" if reason else ""))

        return {"success": True, "queue_id": queue_id, "status": status}
    finally:
        conn.close()
